[package]
name = "ray-tracer-challenge"
version = "0.1.0"
authors = ["lisp-ceo <j@lisp-ceo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
